/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visao;

import java.text.NumberFormat;
import java.util.ArrayList;
import java.util.Locale;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modelo.MesVO;
import modelo.SemanaVO;
import servicos.MesServicos;
import servicos.SemanaServicos;
import servicos.ServicosFactory;

/**
 *
 * @author Lucas
 */
public class GUIFechaSemana extends javax.swing.JInternalFrame {
DefaultTableModel dtm = new DefaultTableModel(
    new Object[][]{},
    new Object[]{"Código", "Dia da Semana", "Valor Total"});
    /**
     * Creates new form GUIFechaSemana
     */
    public GUIFechaSemana() {
        initComponents();
        prencherTabelaSemana();
        IconeTela();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jtSemana = new javax.swing.JTable();
        jbAtualizar = new javax.swing.JButton();
        jbExcluir = new javax.swing.JButton();

        setClosable(true);

        jtSemana.setFocusable(false);
        jtSemana = new javax.swing.JTable(){
            public boolean isCellEditable(int rowIndex, int colIndex){
                return false;
            }
        };
        jtSemana.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Dia da Semana", "Valor Total"
            }
        ));
        jtSemana.getTableHeader().setResizingAllowed(false);
        jtSemana.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(jtSemana);

        jbAtualizar.setText("Atualizar");
        jbAtualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAtualizarActionPerformed(evt);
            }
        });

        jbExcluir.setText("Excluir");
        jbExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbExcluirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jbAtualizar)
                        .addGap(18, 18, 18)
                        .addComponent(jbExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 352, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbAtualizar)
                    .addComponent(jbExcluir))
                .addContainerGap(37, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

       private void IconeTela(){
       String URL = "/icones/icon_title2.png";
       setFrameIcon(new ImageIcon(this.getClass().getResource(URL)));
    }
    
     private void limparTabela(){
           dtm.setNumRows(0);
        }
     
        private void prencherTabelaSemana(){
        try {
           SemanaServicos ss = ServicosFactory.getSemanaServicos();
           
            ArrayList<SemanaVO> semana = new ArrayList<>();
            
            semana = ss.buscarSemana();
            
            NumberFormat nf = NumberFormat.getCurrencyInstance(new Locale("pt", "BR"));            
             
              
            for(int i = 0; i < semana.size(); i++){
               dtm.addRow(new String[]{
                  String.valueOf(semana.get(i).getIdSemana()),
                  String.valueOf(semana.get(i).getSemana()),                  
                   nf.format(semana.get(i).getvTotal())
               });
            }//fecha for
            
            
            jtSemana.setModel(dtm);
            
        } catch (Exception e) {
               JOptionPane.showMessageDialog(
                        null,
                        "Erro ao Prencher tabela da Semana!",
                        "Mensagem de Erro",
                        JOptionPane.ERROR_MESSAGE);
        }//fecha catch
    }//fecha prencher tabela
  
        private void deletarSemana() {
        try {
            
            int linha = jtSemana.getSelectedRow();
            
            
            if (linha == -1) {
     JOptionPane.showMessageDialog(
                        null,
                        "você não selecionou nenhuma linha!",
                        "Mensagem de atenção",
                        JOptionPane.INFORMATION_MESSAGE);
            } else {
                SemanaServicos ss = ServicosFactory.getSemanaServicos();
                
                String idSemana = (String) jtSemana.getValueAt(linha, 0);
                
                ss.deletarSemana(Long.parseLong(idSemana));

                
        JOptionPane.showMessageDialog(
                        null,
                        "Semana excluida com sucesso!",
                        "Mensagem de confirmação",
                        JOptionPane.INFORMATION_MESSAGE);
            }//fecha else
        } catch (Exception e) {
                 JOptionPane.showMessageDialog(
                        null,
                        "erro ao deletar!",
                        "Mensagem de erro",
                        JOptionPane.ERROR_MESSAGE);
        }//fecha catch        
    }//fecha deletar
    
    private void jbAtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAtualizarActionPerformed
        limparTabela();
        prencherTabelaSemana();
    }//GEN-LAST:event_jbAtualizarActionPerformed

    private void jbExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbExcluirActionPerformed
        deletarSemana();
        limparTabela();
        prencherTabelaSemana();
    }//GEN-LAST:event_jbExcluirActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbAtualizar;
    private javax.swing.JButton jbExcluir;
    private javax.swing.JTable jtSemana;
    // End of variables declaration//GEN-END:variables
}
