/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visao;

import com.placeholder.PlaceHolder;
import java.awt.Color;
import java.awt.Image;
import java.awt.Toolkit;
import java.net.URL;
import javax.swing.BorderFactory;
import javax.swing.UIManager;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author braia
 */
public class MenuPrincipal extends javax.swing.JFrame {
 

    DefaultTableModel dtm = new DefaultTableModel(
    new Object[][]{},
    new Object[]{"Código","Nome","Valor custo"});
    
   
    
    /**
     * Creates new form MenuPrincipal
     */
    public MenuPrincipal() {
        initComponents();
        meioTela();
        IconeTela();        
       //customizeMenuBar(jMenuBar1);
       //this.setExtendedState(MAXIMIZED_BOTH);

        
    }
    
    
    private void meioTela(){
        this.setLocationRelativeTo(null);
    }
    
     public void IconeTela(){
        //torcando icone do title da janela
        URL CaminhoIcone = getClass().getResource("/icones/icon_title2.png");
        Image iconeTitulo = Toolkit.getDefaultToolkit().getImage(CaminhoIcone);
        this.setIconImage(iconeTitulo);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem5 = new javax.swing.JMenuItem();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jAreaTrabalho = new javax.swing.JDesktopPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jmCadastrar = new javax.swing.JMenu();
        jmiProduto = new javax.swing.JMenuItem();
        jmiHoraMarcada = new javax.swing.JMenuItem();
        jmFerramentas = new javax.swing.JMenu();
        jmAtendimento = new javax.swing.JMenuItem();
        jmGerenciaAtendimento = new javax.swing.JMenuItem();
        jmiMes = new javax.swing.JMenuItem();
        jmiSemana = new javax.swing.JMenuItem();
        jmiManProdutos = new javax.swing.JMenuItem();
        jmiAgenda = new javax.swing.JMenuItem();
        jmSair = new javax.swing.JMenu();

        jMenuItem5.setText("jMenuItem5");

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2), javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 153, 0), 2)));

        jLabel1.setBorder(BorderFactory.createLineBorder(Color.black));
        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Arial Black", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 153, 0));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/simas3.jpg"))); // NOI18N
        jLabel1.setText("Simas Barbearia Retrô ");
        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(212, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(205, 205, 205))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(jLabel1)
                .addContainerGap(372, Short.MAX_VALUE))
        );

        jAreaTrabalho.setLayer(jPanel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jAreaTrabalhoLayout = new javax.swing.GroupLayout(jAreaTrabalho);
        jAreaTrabalho.setLayout(jAreaTrabalhoLayout);
        jAreaTrabalhoLayout.setHorizontalGroup(
            jAreaTrabalhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jAreaTrabalhoLayout.setVerticalGroup(
            jAreaTrabalhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jMenuBar1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 153, 0), 2));

        jmCadastrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/note.png"))); // NOI18N
        jmCadastrar.setText("Cadastrar");
        jmCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmCadastrarActionPerformed(evt);
            }
        });

        jmiProduto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/barcode.png"))); // NOI18N
        jmiProduto.setText("Produto");
        jmiProduto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jmiProdutoMouseClicked(evt);
            }
        });
        jmiProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiProdutoActionPerformed(evt);
            }
        });
        jmCadastrar.add(jmiProduto);

        jmiHoraMarcada.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/clock.png"))); // NOI18N
        jmiHoraMarcada.setText("Marcar Horário");
        jmiHoraMarcada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiHoraMarcadaActionPerformed(evt);
            }
        });
        jmCadastrar.add(jmiHoraMarcada);

        jMenuBar1.add(jmCadastrar);

        jmFerramentas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/config.png"))); // NOI18N
        jmFerramentas.setText("Ferramentas");

        jmAtendimento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/aten.png"))); // NOI18N
        jmAtendimento.setText("Atendimento");
        jmAtendimento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmAtendimentoActionPerformed(evt);
            }
        });
        jmFerramentas.add(jmAtendimento);

        jmGerenciaAtendimento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/geren.png"))); // NOI18N
        jmGerenciaAtendimento.setText("Gerenciar Atendimentos");
        jmGerenciaAtendimento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmGerenciaAtendimentoActionPerformed(evt);
            }
        });
        jmFerramentas.add(jmGerenciaAtendimento);

        jmiMes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/calendar.png"))); // NOI18N
        jmiMes.setText("Gerenciar Mês");
        jmiMes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiMesActionPerformed(evt);
            }
        });
        jmFerramentas.add(jmiMes);

        jmiSemana.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/agenda2.png"))); // NOI18N
        jmiSemana.setText("Gerenciar Semana");
        jmiSemana.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiSemanaActionPerformed(evt);
            }
        });
        jmFerramentas.add(jmiSemana);

        jmiManProdutos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/maintenance.png"))); // NOI18N
        jmiManProdutos.setText("Gerenciar Produtos");
        jmiManProdutos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jmiManProdutosMouseClicked(evt);
            }
        });
        jmiManProdutos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiManProdutosActionPerformed(evt);
            }
        });
        jmFerramentas.add(jmiManProdutos);

        jmiAgenda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/agenda.png"))); // NOI18N
        jmiAgenda.setText("Agenda");
        jmiAgenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiAgendaActionPerformed(evt);
            }
        });
        jmFerramentas.add(jmiAgenda);

        jMenuBar1.add(jmFerramentas);

        jmSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/exit.png"))); // NOI18N
        jmSair.setText("Sair");
        jmSair.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jmSairMouseClicked(evt);
            }
        });
        jMenuBar1.add(jmSair);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jAreaTrabalho)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jAreaTrabalho)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void abrirCadProduto(){
        GUICadProduto gcp = new GUICadProduto();
        jAreaTrabalho.add(gcp);
        gcp.setVisible(true);
   }//fecha método
    private void abrirAtendimento(){
        GUIAtendimento ga = new GUIAtendimento();
        jAreaTrabalho.add(ga);
        ga.setVisible(true);
    }
      private void abrirManAtendimento(){
        GUIGerenciaAtendimentos gga = new GUIGerenciaAtendimentos();
        jAreaTrabalho.add(gga);
        gga.setVisible(true);
   }//fecha método
 
 private void abrirMarcarHorario(){
       GUIMarcaHorario gmh = new GUIMarcaHorario();
       jAreaTrabalho.add(gmh);
       gmh.setVisible(true);
 }
  private void abrirAgenda(){
       GUIAgendaHorarios gah = new GUIAgendaHorarios();
       jAreaTrabalho.add(gah);
       gah.setVisible(true);
 }
     
    private void abrirManProduto(){
        GUIGerenciaProduto gmp = new GUIGerenciaProduto();
        jAreaTrabalho.add(gmp);
        gmp.setVisible(true);
    }//fecha método
    
        private void abrirManMes(){
            GUIFechaMes gm = new GUIFechaMes(); //fecha método
            jAreaTrabalho.add(gm);
            gm.setVisible(true);
    }
     
        private void abrirManSemana(){
           GUIFechaSemana gm = new GUIFechaSemana(); //fecha método
           jAreaTrabalho.add(gm);
           gm.setVisible(true);
    }
    
//        private void customizeMenuBar(JMenuBar menuBar) {
//
//    menuBar.setUI(new BasicMenuBarUI() {
//
//        @Override
//        public void paint(Graphics g, JComponent c) {
//            g.setColor(Color.WHITE);            
//            g.fillRect(0, 0, c.getWidth(), c.getHeight());
//        }
//
//    });
//
//    MenuElement[] menus = menuBar.getSubElements();
//
//    for (MenuElement menuElement : menus) {
//
//        JMenu menu = (JMenu) menuElement.getComponent();
//        changeComponentColors(menu);
//        menu.setOpaque(true);
//
//        MenuElement[] menuElements = menu.getSubElements();
//
//        for (MenuElement popupMenuElement : menuElements) {
//
//            JPopupMenu popupMenu = (JPopupMenu) popupMenuElement.getComponent();
//            popupMenu.setBorder(null);
//
//            MenuElement[] menuItens = popupMenuElement.getSubElements();
//
//            for (MenuElement menuItemElement : menuItens) {
//
//                JMenuItem menuItem = (JMenuItem) menuItemElement.getComponent();
//                changeComponentColors(menuItem);
//                menuItem.setOpaque(true);
//
//            }
//        }
//    }
//}
//
//private void changeComponentColors(Component comp) {
//    comp.setBackground(Color.LIGHT_GRAY);
//    comp.setForeground(Color.white);
//}
  
    private void jmiProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiProdutoActionPerformed
            abrirCadProduto();
    }//GEN-LAST:event_jmiProdutoActionPerformed

    private void jmiManProdutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiManProdutosActionPerformed
            abrirManProduto();
    }//GEN-LAST:event_jmiManProdutosActionPerformed

    private void jmSairMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jmSairMouseClicked
             System.exit(0);
    }//GEN-LAST:event_jmSairMouseClicked

    private void jmCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmCadastrarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jmCadastrarActionPerformed

    private void jmiManProdutosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jmiManProdutosMouseClicked
            
    }//GEN-LAST:event_jmiManProdutosMouseClicked

    private void jmiProdutoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jmiProdutoMouseClicked

    }//GEN-LAST:event_jmiProdutoMouseClicked

    private void jmiHoraMarcadaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiHoraMarcadaActionPerformed
              abrirMarcarHorario();
    }//GEN-LAST:event_jmiHoraMarcadaActionPerformed

    private void jmiAgendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiAgendaActionPerformed
                abrirAgenda();
    }//GEN-LAST:event_jmiAgendaActionPerformed

    private void jmGerenciaAtendimentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmGerenciaAtendimentoActionPerformed
         abrirManAtendimento();
    }//GEN-LAST:event_jmGerenciaAtendimentoActionPerformed

    private void jmAtendimentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmAtendimentoActionPerformed
         abrirAtendimento();
    }//GEN-LAST:event_jmAtendimentoActionPerformed

    private void jmiMesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiMesActionPerformed
         abrirManMes();
    }//GEN-LAST:event_jmiMesActionPerformed

    private void jmiSemanaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiSemanaActionPerformed
         abrirManSemana();
    }//GEN-LAST:event_jmiSemanaActionPerformed
     
   
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        try {
            UIManager.setLookAndFeel("com.jtattoo.plaf.graphite.GraphiteLookAndFeel");
        } catch (Exception e) {
        }
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new MenuPrincipal().setVisible(true);
            }

       
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane jAreaTrabalho;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable2;
    private javax.swing.JMenuItem jmAtendimento;
    private javax.swing.JMenu jmCadastrar;
    private javax.swing.JMenu jmFerramentas;
    private javax.swing.JMenuItem jmGerenciaAtendimento;
    private javax.swing.JMenu jmSair;
    private javax.swing.JMenuItem jmiAgenda;
    private javax.swing.JMenuItem jmiHoraMarcada;
    private javax.swing.JMenuItem jmiManProdutos;
    private javax.swing.JMenuItem jmiMes;
    private javax.swing.JMenuItem jmiProduto;
    private javax.swing.JMenuItem jmiSemana;
    // End of variables declaration//GEN-END:variables
}
